---
- name: Restart Apache and enable site
  hosts: wordpress
  become: yes
  tasks:
    - name: Configure Apache VirtualHost
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin admin@yourdomain.com
              ServerName 18.221.56.13
              DocumentRoot /var/www/html/wordpress
              <Directory /var/www/html/wordpress>
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Enable WordPress site and Apache mod_rewrite
      shell: |
        a2ensite wordpress
        a2enmod rewrite
        systemctl restart apache2
