---
- name: Install Apache, PHP, and dependencies
  hosts: wordpress
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache and PHP dependencies
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - unzip
          - curl
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes
